"""user birthday

Revision ID: 1befe361a34
Revises: 53fb5dd0aac
Create Date: 2015-04-18 17:07:23.537876

"""

# revision identifiers, used by Alembic.
revision = '1befe361a34'
down_revision = '53fb5dd0aac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday')
    ### end Alembic commands ###
